name: CMake

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: |
          cd Team00/Code00
          mkdir build
          cd build
          cmake -A Win32 ..
          cmake --build . --target unit_testing --config Release
          cmake --build . --target integration_testing --config Release
          cmake --build . --target autotester --config Release

      - name: List Files in Release
        working-directory: ./Team00/Code00/build/src/unit_testing/Release
        run: ls

      - name: Unit Test
        working-directory: ./Team00/Code00/build/src/unit_testing/Release
        run: ./unit_testing.exe -d yes

      - name: Integration Test
        working-directory: ./Team00/Code00/build/src/integration_testing/Release
        run: ./integration_testing.exe -d yes

  macos-build:
    runs-on: macos-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        working-directory: ./Team00/Code00
        run: cmake -B build/ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        working-directory: ./Team00/Code00
        run: cmake --build build/ --config ${{env.BUILD_TYPE}}

      - name: Unit & Integration Test
        working-directory: ./Team00/Code00/build/src/
        run: |
          unit_testing/unit_testing -d yes
          integration_testing/integration_testing -d yes

  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install cpplint
      - run: |
          cpplint \
          --filter=-legal/copyright,-build/header_guard,-build/namespaces,-runtime/int \
          --exclude=Team00/Code00/lib/ \
          --exclude=Team00/Code00/cmake-build-debug/ \
          --exclude=Team00/Code00/src/autotester/ \
          --exclude=Team00/Code00/src/autotester_gui/ \
          --recursive .
